# Generated by Django 4.1.5 on 2024-02-21 16:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_personalinfo'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PersonalInfo',
        ),
    ]
