# Generated by Django 4.1.5 on 2024-03-04 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_project'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='project',
            options={'ordering': ('order',), 'verbose_name': 'Project Setting', 'verbose_name_plural': 'Project Settings'},
        ),
        migrations.AddField(
            model_name='project',
            name='order',
            field=models.IntegerField(default=0, verbose_name='Order'),
        ),
    ]
